[project]
name = "dj-m"
version = "0.1.0"
dependencies = [
    "click",
    "django>5,<5.1",
    "django-debug-toolbar",
    "django-extensions",
    "python-webpack-boilerplate",
]

[tool.setuptools]
packages = ["dj_m"]

[project.scripts]
dj = "dj_m:cli"
